name: madperfume
description: MAD Perfume mobile app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  dio: ^5.9.0
  google_fonts: ^6.3.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
