const Map<String, String> arSa = {
  'app_name': 'MAD PERFUME',
  'tagline': 'أناقة غير مرئية',
  'welcome_headline': 'أناقة غير مرئية في كل قطرة.',
  'welcome_body':
      'اكتشف عالماً منسقاً من العطور الحرفية المصممة لمن يبحث عن الاستثنائي.',
  'collection_year': 'مجموعة 2024',
  'sign_up': 'إنشاء حساب',
  'login': 'تسجيل الدخول',
  'terms_prefix': 'بالمتابعة فإنك توافق على',
  'terms': 'شروط الخدمة',
  'welcome_back': 'مرحباً بعودتك',
  'sign_in_subtitle': 'سجّل الدخول للوصول إلى مجموعتك.',
  'email_or_phone': 'البريد أو الهاتف',
  'enter_your_details': 'أدخل بياناتك',
  'password': 'كلمة المرور',
  'forgot_password': 'نسيت كلمة المرور؟',
  'no_account': 'ليس لديك حساب؟',
  'create_account': 'إنشاء حساب',
  'create_your_account': 'أنشئ حسابك',
  'join_world': 'انضم إلى عالم الأناقة غير المرئية والعطور الحرفية.',
  'full_name': 'الاسم الكامل',
  'email_address': 'البريد الإلكتروني',
  'phone_number': 'رقم الهاتف',
  'confirm': 'تأكيد',
  'or_sign_up_with': 'أو سجّل عبر',
  'google': 'Google',
  'apple': 'Apple',
  'have_account': 'لديك حساب بالفعل؟',
  'reset_password': 'إعادة تعيين كلمة المرور',
  'reset_password_body': 'أرسلنا رمز تحقق مكوناً من 6 أرقام إلى بريدك المسجّل.',
  'verify_code': 'تحقق من الرمز',
  'didnt_receive': 'لم يصلك الرمز؟',
  'resend_code': 'إعادة الإرسال',
  'forgot_title': 'نسيت كلمة المرور',
  'forgot_body': 'أدخل بريدك المسجّل وسنرسل رمز التحقق.',
  'send_code': 'إرسال الرمز',
  'hello': 'مرحباً، الجميلة',
  'discover_scent': 'اكتشف عطرك.',
  'search_hint': 'ابحث عن عطور، نوتات، علامات...',
  'no_results': 'لا توجد نتائج',
  'new_collection': 'مجموعة جديدة',
  'all_collection': 'كل المجموعات',
  'view_all': 'عرض الكل',
  'featured': 'مختارات مميزة',
  'our_boutiques': 'البوتيكات لدينا',
  'home': 'الرئيسية',
  'products': 'المنتجات',
  'cart': 'السلة',
  'loyalty': 'الولاء',
  'profile': 'الملف',
  'notifications': 'الإشعارات',
  'notifications_subtitle': 'ابقَ على اطلاع بعطورك ومكافآتك والعروض الحصرية.',
  'all_updates': 'كل التحديثات',
  'offers': 'عروض',
  'reward': 'مكافأة',
  'offers_curations': 'عروض وتنسيقات',
  'loyalty_rewards': 'ولاء ومكافآت',
  'order_status': 'حالة الطلب',
  'select_language': 'اختر اللغة',
  'arabic': 'العربية',
  'hebrew': 'العبرية',
  'english': 'الإنجليزية',
  'united_kingdom': 'المملكة المتحدة',
  'apply_changes': 'تطبيق التغييرات',
  'product_category': 'فئات المنتجات',
  'the_collections': 'المجموعات',
  'collections_intro':
      'اكتشف عطرك المميز عبر عائلاتنا الشمية المنسقة بدقة وأناقة غير مرئية.',
  'olfactive_family': 'عائلة شمية',
  'product_list': 'قائمة المنتجات',
  'search_products': 'ابحث عن منتجات',
  'sort_newest': 'الأحدث',
  'product_details': 'تفاصيل المنتج',
  'eau_de_parfum': 'أو دو بارفان',
  'available_at': 'متوفر في',
  'reviews': 'التقييمات',
  'based_on': 'بناءً على %s تقييماً',
  'add_to_cart': 'أضف إلى السلة',
  'shopping_bag': 'حقيبة التسوق',
  'items_in_collection': 'لديك %s قطعاً في مجموعتك.',
  'subtotal': 'المجموع الفرعي',
  'proceed_checkout': 'متابعة الدفع',
  'checkout': 'الدفع',
  'checkout_title': 'إتمام الطلب',
  'checkout_subtitle': 'أكمل طلبك من الجواهر المنسقة.',
  'shipping_information': 'معلومات الشحن',
  'enter_your_name': 'أدخل اسمك',
  'name': 'الاسم',
  'street_address': 'عنوان الشارع',
  'city': 'المدينة',
  'payment_details': 'تفاصيل الدفع',
  'visa_credit': 'فيزا / بطاقة ائتمان',
  'cash_on_delivery': 'الدفع عند الاستلام',
  'card_number': 'رقم البطاقة',
  'mm_yy': 'شهر / سنة',
  'order_summary': 'ملخص الطلب',
  'shipping': 'الشحن',
  'taxes': 'الضرائب',
  'free': 'مجاني',
  'total': 'الإجمالي',
  'secure_checkout': 'دفع آمن',
  'apply_voucher': 'تطبيق القسيمة',
  'apply_voucher_copy':
      'اختر قسيمة خصم غير مستخدمة. تُخصم من المجموع قبل الضريبة، ولا تجعل الإجمالي أقل من صفر.',
  'no_usable_vouchers':
      'لا توجد قسائم خصم غير مستخدمة بعد. استبدل مكافأة خصم أولاً ثم عد إلى هنا.',
  'redeem_for_voucher': 'استبدل قسيمة',
  'discount': 'الخصم',
  'voucher_checkout_copy':
      'طبّق هذه القسيمة عند الدفع لخصم قيمتها من الطلب قبل الضريبة. يمكنك أيضاً عرض الرمز في أحد الفروع.',
  'used_on_order': 'استُخدمت على %s',
  'used': 'مستخدمة',
  'use_loyalty_points': 'استخدم نقاط الولاء',
  'points_available': '%s نقطة متاحة',
  'points_discount': 'خصم النقاط',
  'order_successful': 'تم الطلب بنجاح',
  'order_success_body':
      'بدأت رحلة عطرك. أرسلنا رسالة تأكيد بكل تفاصيل اختيارك.',
  'track_order': 'تتبع الطلب',
  'back_to_home': 'العودة للرئيسية',
  'order_tracking': 'تتبع الطلب',
  'track_your_order': 'تتبع طلبك',
  'order_in_transit_copy': 'الطلب %s في الطريق إليك. التسليم المتوقع %s.',
  'order_details': 'تفاصيل الطلب',
  'shipping_journey': 'رحلة الشحن',
  'delivery_address': 'عنوان التسليم',
  'payment': 'الدفع',
  'loyalty_member': 'عضو الولاء',
  'total_points_available': 'إجمالي النقاط المتاحة',
  'platinum': 'بلاتينيوم',
  'earn_points': 'اكسب نقاطاً',
  'earn_points_copy':
      'استكشف عطوراً جديدة وشارك تجربتك لجمع المزيد من المكافآت.',
  'redeem_rewards': 'استبدل المكافآت',
  'redeem_rewards_copy':
      'استخدم نقاطك لمنتجات حصرية وتجارب البوتيك والمجموعات المنسقة.',
  'explore_rewards': 'استكشف المكافآت',
  'view_rewards_journey': 'عرض رحلة المكافآت',
  'recent_activity': 'النشاط الأخير',
  'earn_points_title': 'معلومات كسب النقاط',
  'elevate_senses': 'ارتقِ بحواسك واكسب المكافآت',
  'earn_intro':
      'رحلتك مع MAD PERFUME أكثر من عملية شراء. إنها تراكم امتياز. اكتشف كيف تنمو مجموعتك مع كسب نقاط حصرية.',
  'in_app_purchases': 'مشتريات التطبيق',
  'in_app_copy':
      'اكسب نقاطاً لكل منتج تكمله من مجموعة. لكل مجموعة قيمة استبدال يحددها لوحة التحكم.',
  'physical_boutiques': 'البوتيكات الفعلية',
  'physical_copy':
      'زر أيّاً من أتولييهاتنا الفاخرة وقدّم محفظتك الرقمية لرفع النقاط.',
  'rewards_experience': 'تجربة المكافآت',
  'step_browse': 'تصفح',
  'step_browse_copy':
      'تصفح كتالوجنا المنسق من العطور المتخصصة وإضافات البوتيك.',
  'step_collect': 'اجمع',
  'step_collect_copy':
      'تُضاف النقاط تلقائياً إلى محفظتك الرقمية بعد إتمام الدفع.',
  'step_redeem': 'استبدل',
  'step_redeem_copy':
      'استخدم نقاطك لخصومات حصرية أو دخول الأتولييه أو تجارب الهدايا.',
  'rewards': 'المكافآت',
  'exclusive_rewards': 'مكافآت حصرية',
  'exclusive_rewards_copy': 'بدّل نقاطك بتجارب فاخرة وإصدارات محدودة.',
  'view_personal_rewards': 'عرض مكافآتك',
  'redeem': 'استبدال',
  'unavailable': 'غير متاح',
  'redeemed': 'تم الاستبدال',
  'reward_details': 'تفاصيل المكافأة',
  'how_to_use': 'كيفية الاستخدام',
  'redeem_now': 'استبدل الآن',
  'redeemed_rewards': 'المكافآت المستبدلة',
  'your_exclusive': 'مجموعتك الحصرية',
  'points_history': 'سجل النقاط',
  'filter_transactions': 'تصفية العمليات',
  'earned': 'مكتسب',
  'spent': 'مستخدم',
  'order_history': 'سجل الطلبات',
  'others': 'أخرى',
  'recent_transactions': 'العمليات الأخيرة',
  'all_orders': 'كل الطلبات',
  'saved_items_count': 'العناصر المحفوظة',
  'tier_status': 'مستوى العضوية',
  'explore_saved_items': 'استكشف المحفوظات',
  'profile_and_settings': 'الملف والإعدادات',
  'settings': 'الإعدادات',
  'edit_profile': 'تعديل الملف',
  'security': 'الأمان',
  'logout': 'تسجيل الخروج',
  'save_changes': 'حفظ التغييرات',
  'update_password': 'تحديث كلمة المرور',
  'current_password': 'كلمة المرور الحالية',
  'new_password': 'كلمة المرور الجديدة',
  'confirm_password': 'تأكيد كلمة المرور',
  'update_password_btn': 'تحديث كلمة المرور',
  'stay_inspired': 'ابقَ ملهماً',
  'preference_center': 'مركز التفضيلات',
  'preference_copy': 'اختر قصص العطور التي تصلك.',
  'promotional_offers': 'عروض ترويجية',
  'exclusive_releases': 'إصدارات حصرية',
  'member_status_update': 'تحديث حالة العضوية',
  'saved_items': 'العناصر المحفوظة',
  'your_private_collection': 'مجموعتك الخاصة',
  'write_a_review': 'اكتب تقييماً',
  'already_reviewed': 'لقد قيّمت هذا المنتج بالفعل',
  'share_thoughts': 'شارك رأيك',
  'publish_review': 'نشر التقييم',
  'branches': 'الفروع',
  'physical_ateliers': 'أتولييهات فعلية',
  'branches_intro':
      'اختبر عطورنا شخصياً. كل أتولييه ملاذ حسي يعكس التزامنا بالأناقة غير المرئية.',
  'search_city': 'ابحث عن مدينة أو شارع...',
  'branch_details': 'تفاصيل الفرع',
  'flagship_boutique': 'بوتيك رئيسي',
  'address': 'العنوان',
  'contact': 'التواصل',
  'hours': 'الساعات',
  'required_field': 'هذا الحقل مطلوب',
  'invalid_email': 'أدخل بريداً صالحاً',
  'invalid_phone': 'أدخل رقم هاتف صالحاً',
  'invalid_password':
      'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل وتتضمن رقماً ورمزاً خاصاً',
  'password_mismatch': 'كلمتا المرور غير متطابقتين',
  'invalid_code': 'أدخل الرمز المكون من 6 أرقام',
  'login_failed': 'تعذر تسجيل الدخول بهذه البيانات',
  'empty_cart': 'مجموعتك فارغة',
  'empty_saved': 'لا توجد قطع محفوظة بعد',
  'empty_orders': 'لا توجد طلبات بعد',
  'empty_rewards': 'لا توجد مكافآت مستبدلة بعد',
  'retry': 'حاول مرة أخرى',
  'floral': 'زهري',
  'woody': 'خشبي',
  'oriental': 'شرقي',
  'fresh': 'منعش',
  'leather': 'جلدي',
  'gourmand': 'حلوي',
  'fresh_citrus': 'حمضيات منعشة',
  'language': 'اللغة',
  'resend_in': 'إعادة الإرسال خلال %sث',
  'qty': 'الكمية',
  'remove': 'إزالة',
  'not_enough_points': 'النقاط غير كافية',
  'already_redeemed': 'تم الاستبدال مسبقاً',
  'card_invalid': 'أدخل رقم بطاقة صالحاً',
  'expiry_invalid': 'أدخل تاريخ انتهاء صالحاً',
  'fill_shipping': 'أكمل بيانات الشحن',
  'select_payment': 'اختر طريقة الدفع',
  'review_hint': 'اكتب تقييمك',
  'rating_required': 'اختر تقييماً',
  'code_sent': 'تم إرسال الرمز',
  'social_continue': 'متابعة',
  'social_unavailable':
      'تسجيل الدخول عبر Google وApple غير متاح في واجهة API المقدمة',
  'stripe_unavailable': 'الدفع بالبطاقة يتطلب إعداد Stripe PaymentSheet',
  'please_wait': 'يرجى الانتظار...',
  'product_added_successfully': 'تمت إضافة المنتج بنجاح',
  'change_profile_photo': 'تغيير صورة الملف الشخصي',
  'invalid_avatar': 'اختر صورة PNG أو JPG أو WebP بحجم لا يتجاوز 10 ميغابايت',
  'voucher_code': 'رمز القسيمة',
  'reward_claim_copy':
      'اعرض رمز القسيمة في أحد الفروع لاستلام مكافأتك. تبقى قيد التجهيز حتى يسلمها موظف الفرع، ثم تصبح مستلمة.',
  'status': 'الحالة',
  'filter': 'تصفية',
  'newest': 'الأحدث',
  'price': 'السعر',
  'in_transit': 'قيد التوصيل',
  'delivered': 'تم التوصيل',
  'processing': 'قيد التجهيز',
  'shipped': 'تم الشحن',
  'order_placed': 'تم إنشاء الطلب',
  'estimated_arrival': 'الوصول المتوقع',
  'complimentary': 'مجاني',
};
