const Map<String, String> enUs = {
  'app_name': 'MAD PERFUME',
  'tagline': 'INVISIBLE ELEGANCE',
  'welcome_headline': 'Invisible Elegance in Every Drop.',
  'welcome_body':
      'Discover a curated world of artisanal fragrances designed for those who seek the extraordinary.',
  'collection_year': 'COLLECTION 2024',
  'sign_up': 'Sign Up',
  'login': 'Login',
  'terms_prefix': 'BY CONTINUING YOU ADHERE TO OUR',
  'terms': 'TERMS OF SERVICE',
  'welcome_back': 'Welcome Back',
  'sign_in_subtitle': 'Sign in to access your collection.',
  'email_or_phone': 'Email or Phone',
  'enter_your_details': 'Enter your details',
  'password': 'Password',
  'forgot_password': 'Forgot Password?',
  'no_account': "Don't have an account?",
  'create_account': 'Create Account',
  'create_your_account': 'Create your account',
  'join_world': 'Join the world of invisible elegance and artisanal scents.',
  'full_name': 'Full Name',
  'email_address': 'Email Address',
  'phone_number': 'Phone Number',
  'confirm': 'Confirm',
  'or_sign_up_with': 'OR SIGN UP WITH',
  'google': 'Google',
  'apple': 'Apple',
  'have_account': 'Already have an account?',
  'reset_password': 'Reset Password',
  'reset_password_body':
      'We have sent a 6-digit verification code to your registered email address.',
  'verify_code': 'VERIFY CODE',
  'didnt_receive': "Didn't receive the code?",
  'resend_code': 'RESEND CODE',
  'forgot_title': 'Forgot Password',
  'forgot_body':
      'Enter your registered email and we will send a verification code.',
  'send_code': 'SEND CODE',
  'hello': 'Hello, Beautiful',
  'discover_scent': 'Discover your scent.',
  'search_hint': 'Search for perfumes, notes, brands...',
  'no_results': 'No matching scents',
  'new_collection': 'NEW COLLECTION',
  'all_collection': 'All Collection',
  'view_all': 'VIEW ALL',
  'featured': 'Featured Selection',
  'our_boutiques': 'Our Boutiques',
  'home': 'Home',
  'products': 'Products',
  'cart': 'Cart',
  'loyalty': 'Loyalty',
  'profile': 'Profile',
  'notifications': 'Notifications',
  'notifications_subtitle':
      'Stay updated on your scents, rewards, and exclusive offers.',
  'all_updates': 'ALL UPDATES',
  'offers': 'OFFERS',
  'reward': 'REWARD',
  'offers_curations': 'OFFERS & CURATIONS',
  'loyalty_rewards': 'LOYALTY & REWARDS',
  'order_status': 'ORDER STATUS',
  'select_language': 'Select Language',
  'arabic': 'Arabic',
  'hebrew': 'Hebrew',
  'english': 'English',
  'united_kingdom': 'United Kingdom',
  'apply_changes': 'APPLY CHANGES',
  'product_category': 'PRODUCT CATEGORY',
  'the_collections': 'The Collections',
  'collections_intro':
      'Discover your signature scent through our curated olfactory families, crafted with precision and invisible elegance.',
  'olfactive_family': 'OLFACTIVE FAMILY',
  'product_list': 'PRODUCT LIST',
  'search_products': 'Search products',
  'sort_newest': 'NEWEST',
  'product_details': 'PRODUCT DETAILS',
  'eau_de_parfum': 'EAU DE PARFUM',
  'available_at': 'Available at',
  'reviews': 'Reviews',
  'based_on': 'BASED ON %s REVIEWS',
  'add_to_cart': 'ADD TO CART',
  'shopping_bag': 'Shopping Bag',
  'items_in_collection': 'You have %s items in your collection.',
  'subtotal': 'SUBTOTAL',
  'proceed_checkout': 'PROCEED TO CHECKOUT',
  'checkout': 'CHECKOUT',
  'checkout_title': 'Checkout',
  'checkout_subtitle': 'Complete your order of curated essences.',
  'shipping_information': 'Shipping Information',
  'enter_your_name': 'ENTER YOUR NAME',
  'name': 'Name',
  'street_address': 'STREET ADDRESS',
  'city': 'CITY',
  'payment_details': 'Payment Details',
  'visa_credit': 'Visa / Credit Card',
  'cash_on_delivery': 'Cash on Delivery',
  'card_number': 'CARD NUMBER',
  'mm_yy': 'MM / YY',
  'order_summary': 'Order Summary',
  'shipping': 'Shipping',
  'taxes': 'Taxes',
  'free': 'Free',
  'total': 'Total',
  'secure_checkout': 'SECURE CHECKOUT',
  'apply_voucher': 'Apply voucher',
  'apply_voucher_copy':
      'Choose an unused discount voucher. It comes off your subtotal before tax, and never takes the total below zero.',
  'no_usable_vouchers':
      'No unused discount vouchers yet. Redeem a money-off reward first, then return here.',
  'redeem_for_voucher': 'REDEEM A VOUCHER',
  'discount': 'Discount',
  'voucher_checkout_copy':
      'Apply this voucher at checkout to take its value off your order before tax. You can also show the code in a boutique.',
  'used_on_order': 'Used on %s',
  'used': 'Used',
  'use_loyalty_points': 'Use loyalty points',
  'points_available': '%s pts available',
  'points_discount': 'Points discount',
  'order_successful': 'Order Successful',
  'order_success_body':
      'Your fragrance journey has begun. We have sent a confirmation email with all the details of your selection.',
  'track_order': 'TRACK ORDER',
  'back_to_home': 'Back to Home',
  'order_tracking': 'ORDER TRACKING',
  'track_your_order': 'Track Your Order',
  'order_in_transit_copy':
      'Order %s is currently on its way to you. Expected delivery by %s.',
  'order_details': 'Order Details',
  'shipping_journey': 'Shipping Journey',
  'delivery_address': 'DELIVERY ADDRESS',
  'payment': 'PAYMENT',
  'loyalty_member': 'LOYALTY MEMBER',
  'total_points_available': 'TOTAL POINTS AVAILABLE',
  'platinum': 'Platinum',
  'earn_points': 'Earn Points',
  'earn_points_copy':
      'Explore new scents and share your experience to collect more rewards.',
  'redeem_rewards': 'Redeem Rewards',
  'redeem_rewards_copy':
      'Use your points for exclusive products, boutique experiences, and curated collections.',
  'explore_rewards': 'EXPLORE REWARDS',
  'view_rewards_journey': 'VIEW REWARDS JOURNEY',
  'recent_activity': 'RECENT ACTIVITY',
  'earn_points_title': 'EARN POINTS INFORMATION',
  'elevate_senses': 'Elevate Your Senses, Earn Rewards',
  'earn_intro':
      'Your journey with MAD PERFUME is more than a purchase. It is an accumulation of privilege. Discover how to grow your collection while earning exclusive points.',
  'in_app_purchases': 'In-App Purchases',
  'in_app_copy':
      'Earn points for every product you complete from a collection. Each collection carries its own redeem value set from the dashboard.',
  'physical_boutiques': 'Physical Boutiques',
  'physical_copy':
      'Visit any of our flagship ateliers and present your digital wallet for a points lift on your signature scent.',
  'rewards_experience': 'The Rewards Experience',
  'step_browse': 'Browse',
  'step_browse_copy':
      'Browse our curated catalogue of niche fragrances and boutique extras.',
  'step_collect': 'Collect',
  'step_collect_copy':
      'Points are automatically added to your digital wallet upon successful checkout.',
  'step_redeem': 'Redeem',
  'step_redeem_copy':
      'Use your points for exclusive discounts, atelier access, or gift experiences.',
  'rewards': 'REWARDS',
  'exclusive_rewards': 'Exclusive Rewards',
  'exclusive_rewards_copy':
      'Exchange your points for luxury experiences and limited editions.',
  'view_personal_rewards': 'VIEW PERSONAL REWARDS',
  'redeem': 'REDEEM',
  'unavailable': 'UNAVAILABLE',
  'redeemed': 'Redeemed',
  'reward_details': 'REWARD DETAILS',
  'how_to_use': 'HOW TO USE',
  'redeem_now': 'REDEEM NOW',
  'redeemed_rewards': 'REDEEMED REWARDS',
  'your_exclusive': 'Your Exclusive Collection',
  'points_history': 'POINTS HISTORY',
  'filter_transactions': 'Filter Transactions',
  'earned': 'Earned',
  'spent': 'Spent',
  'order_history': 'Order History',
  'others': 'Others',
  'recent_transactions': 'RECENT TRANSACTIONS',
  'all_orders': 'ALL ORDERS',
  'saved_items_count': 'SAVED ITEMS',
  'tier_status': 'TIER STATUS',
  'explore_saved_items': 'EXPLORE SAVED ITEMS',
  'profile_and_settings': 'PROFILE AND SETTINGS',
  'settings': 'SETTINGS',
  'edit_profile': 'Edit Profile',
  'security': 'Security',
  'logout': 'Logout',
  'save_changes': 'SAVE CHANGES',
  'update_password': 'Update Password',
  'current_password': 'CURRENT PASSWORD',
  'new_password': 'NEW PASSWORD',
  'confirm_password': 'CONFIRM PASSWORD',
  'update_password_btn': 'UPDATE PASSWORD',
  'stay_inspired': 'STAY INSPIRED',
  'preference_center': 'Preference Center',
  'preference_copy':
      'Keep yourself inspired by selecting which scent stories find their way to you.',
  'promotional_offers': 'Promotional Offers',
  'exclusive_releases': 'Exclusive Releases',
  'member_status_update': 'Member Status Update',
  'saved_items': 'SAVED ITEMS',
  'your_private_collection': 'Your Private Collection',
  'write_a_review': 'Write a Review',
  'already_reviewed': 'You already reviewed this product',
  'share_thoughts': 'Share your thoughts',
  'publish_review': 'PUBLISH REVIEW',
  'branches': 'BRANCHES',
  'physical_ateliers': 'Physical Ateliers',
  'branches_intro':
      'Experience our fragrances in person. Each atelier is designed as a sensory sanctuary, reflecting our commitment to invisible elegance and olfactory craftsmanship.',
  'search_city': 'Search city or street...',
  'branch_details': 'BRANCH DETAILS',
  'flagship_boutique': 'FLAGSHIP BOUTIQUE',
  'address': 'Address',
  'contact': 'Contact',
  'hours': 'Hours',
  'required_field': 'This field is required',
  'invalid_email': 'Enter a valid email',
  'invalid_phone': 'Enter a valid phone number',
  'invalid_password':
      'Password must be at least 8 characters with a number and special character',
  'password_mismatch': 'Passwords do not match',
  'invalid_code': 'Enter the 6-digit code',
  'login_failed': 'Unable to sign in with these details',
  'empty_cart': 'Your collection is empty',
  'empty_saved': 'No saved pieces yet',
  'empty_orders': 'No orders yet',
  'empty_rewards': 'No redeemed rewards yet',
  'retry': 'Try again',
  'floral': 'Floral',
  'woody': 'Woody',
  'oriental': 'Oriental',
  'fresh': 'Fresh',
  'leather': 'Leather',
  'gourmand': 'Gourmand',
  'fresh_citrus': 'Fresh Citrus',
  'language': 'Language',
  'resend_in': 'Resend in %ss',
  'qty': 'Qty',
  'remove': 'Remove',
  'not_enough_points': 'Not enough points',
  'already_redeemed': 'Already redeemed',
  'card_invalid': 'Enter a valid card number',
  'expiry_invalid': 'Enter a valid expiry',
  'fill_shipping': 'Complete shipping details',
  'select_payment': 'Select a payment method',
  'review_hint': 'Write your review',
  'rating_required': 'Select a rating',
  'code_sent': 'Code sent',
  'social_continue': 'Continue',
  'social_unavailable':
      'Google and Apple sign-in are not available in the provided API',
  'stripe_unavailable':
      'Card payment requires Stripe PaymentSheet configuration',
  'please_wait': 'PLEASE WAIT...',
  'product_added_successfully': 'Product added successfully',
  'change_profile_photo': 'Change profile photo',
  'invalid_avatar': 'Choose a PNG, JPG or WebP image up to 10MB',
  'voucher_code': 'VOUCHER CODE',
  'reward_claim_copy':
      'Show this voucher code at a boutique to collect your reward. It stays processing until boutique staff hand it over, then becomes delivered.',
  'status': 'Status',
  'filter': 'Filter',
  'newest': 'Newest',
  'price': 'Price',
  'in_transit': 'In transit',
  'delivered': 'Delivered',
  'processing': 'Processing',
  'shipped': 'Shipped',
  'order_placed': 'Order Placed',
  'estimated_arrival': 'Estimated Arrival',
  'complimentary': 'Complimentary',
};
