const Map<String, String> heIl = {
  'app_name': 'MAD PERFUME',
  'tagline': 'אלגנטיות בלתי נראית',
  'welcome_headline': 'אלגנטיות בלתי נראית בכל טיפה.',
  'welcome_body':
      'גלו עולם אוצר של ניחוחות אומנותיים שעוצבו עבור מי שמחפש את יוצא הדופן.',
  'collection_year': 'קולקציה 2024',
  'sign_up': 'הרשמה',
  'login': 'התחברות',
  'terms_prefix': 'בהמשך אתם מאשרים את',
  'terms': 'תנאי השימוש',
  'welcome_back': 'ברוכים השבים',
  'sign_in_subtitle': 'התחברו כדי לגשת לקולקציה שלכם.',
  'email_or_phone': 'אימייל או טלפון',
  'enter_your_details': 'הזינו את הפרטים',
  'password': 'סיסמה',
  'forgot_password': 'שכחתם סיסמה?',
  'no_account': 'אין לכם חשבון?',
  'create_account': 'יצירת חשבון',
  'create_your_account': 'צרו את החשבון',
  'join_world': 'הצטרפו לעולם של אלגנטיות בלתי נראית וניחוחות אומנותיים.',
  'full_name': 'שם מלא',
  'email_address': 'כתובת אימייל',
  'phone_number': 'מספר טלפון',
  'confirm': 'אימות',
  'or_sign_up_with': 'או הרשמה באמצעות',
  'google': 'Google',
  'apple': 'Apple',
  'have_account': 'כבר יש לכם חשבון?',
  'reset_password': 'איפוס סיסמה',
  'reset_password_body': 'שלחנו קוד אימות בן 6 ספרות לאימייל הרשום שלכם.',
  'verify_code': 'אימות קוד',
  'didnt_receive': 'לא קיבלתם את הקוד?',
  'resend_code': 'שלחו שוב',
  'forgot_title': 'שכחתם סיסמה',
  'forgot_body': 'הזינו את האימייל הרשום ונשלח קוד אימות.',
  'send_code': 'שלחו קוד',
  'hello': 'שלום, יפה',
  'discover_scent': 'גלו את הניחוח שלכם.',
  'search_hint': 'חיפוש בשמים, תווים, מותגים...',
  'no_results': 'אין תוצאות תואמות',
  'new_collection': 'קולקציה חדשה',
  'all_collection': 'כל הקולקציות',
  'view_all': 'הצג הכל',
  'featured': 'מבחר מומלץ',
  'our_boutiques': 'הבוטיקים שלנו',
  'home': 'בית',
  'products': 'מוצרים',
  'cart': 'עגלה',
  'loyalty': 'נאמנות',
  'profile': 'פרופיל',
  'notifications': 'התראות',
  'notifications_subtitle': 'הישארו מעודכנים בניחוחות, בפרסים ובהצעות בלעדיות.',
  'all_updates': 'כל העדכונים',
  'offers': 'הצעות',
  'reward': 'פרס',
  'offers_curations': 'הצעות ואוצרות',
  'loyalty_rewards': 'נאמנות ופרסים',
  'order_status': 'סטטוס הזמנה',
  'select_language': 'בחירת שפה',
  'arabic': 'ערבית',
  'hebrew': 'עברית',
  'english': 'אנגלית',
  'united_kingdom': 'הממלכה המאוחדת',
  'apply_changes': 'החל שינויים',
  'product_category': 'קטגוריות מוצר',
  'the_collections': 'הקולקציות',
  'collections_intro':
      'גלו את ניחוח החתימה שלכם דרך משפחות ריח אוצרות, שנוצרו בדיוק ובאלגנטיות בלתי נראית.',
  'olfactive_family': 'משפחת ריח',
  'product_list': 'רשימת מוצרים',
  'search_products': 'חיפוש מוצרים',
  'sort_newest': 'החדש ביותר',
  'product_details': 'פרטי מוצר',
  'eau_de_parfum': 'או דה פרפיום',
  'available_at': 'זמין ב',
  'reviews': 'ביקורות',
  'based_on': 'מבוסס על %s ביקורות',
  'add_to_cart': 'הוספה לעגלה',
  'shopping_bag': 'תיק קניות',
  'items_in_collection': 'יש לכם %s פריטים בקולקציה.',
  'subtotal': 'סכום ביניים',
  'proceed_checkout': 'המשך לתשלום',
  'checkout': 'תשלום',
  'checkout_title': 'סיום הזמנה',
  'checkout_subtitle': 'השלימו את הזמנת התמציות האוצרות שלכם.',
  'shipping_information': 'פרטי משלוח',
  'enter_your_name': 'הזינו שם',
  'name': 'שם',
  'street_address': 'כתובת',
  'city': 'עיר',
  'payment_details': 'פרטי תשלום',
  'visa_credit': 'ויזה / כרטיס אשראי',
  'cash_on_delivery': 'תשלום במסירה',
  'card_number': 'מספר כרטיס',
  'mm_yy': 'MM / YY',
  'order_summary': 'סיכום הזמנה',
  'shipping': 'משלוח',
  'taxes': 'מיסים',
  'free': 'חינם',
  'total': 'סה״כ',
  'secure_checkout': 'תשלום מאובטח',
  'use_loyalty_points': 'שימוש בנקודות נאמנות',
  'points_available': '%s נקודות זמינות',
  'points_discount': 'הנחת נקודות',
  'order_successful': 'ההזמנה בוצעה',
  'order_success_body': 'מסע הניחוח שלכם החל. שלחנו אימייל אישור עם כל פרטי הבחירה.',
  'track_order': 'מעקב הזמנה',
  'back_to_home': 'חזרה לבית',
  'order_tracking': 'מעקב הזמנה',
  'track_your_order': 'עקבו אחר ההזמנה',
  'order_in_transit_copy': 'הזמנה %s בדרך אליכם. משלוח צפוי ב-%s.',
  'order_details': 'פרטי הזמנה',
  'shipping_journey': 'מסע המשלוח',
  'delivery_address': 'כתובת למשלוח',
  'payment': 'תשלום',
  'loyalty_member': 'חבר מועדון',
  'total_points_available': 'סה״כ נקודות זמינות',
  'platinum': 'פלטינום',
  'earn_points': 'צבירת נקודות',
  'earn_points_copy': 'גלו ניחוחות חדשים ושתפו חוויה כדי לאסוף עוד פרסים.',
  'redeem_rewards': 'מימוש פרסים',
  'redeem_rewards_copy': 'השתמשו בנקודות למוצרים בלעדיים, חוויות בוטיק וקולקציות אוצרות.',
  'explore_rewards': 'גלו פרסים',
  'view_rewards_journey': 'צפו במסע הפרסים',
  'recent_activity': 'פעילות אחרונה',
  'earn_points_title': 'מידע על צבירת נקודות',
  'elevate_senses': 'העלו את החושים, צברו פרסים',
  'earn_intro':
      'המסע עם MAD PERFUME הוא יותר מרכישה. זהו צבירת זכות. גלו כיצד הקולקציה גדלה תוך צבירת נקודות בלעדיות.',
  'in_app_purchases': 'רכישות באפליקציה',
  'in_app_copy':
      'צברו נקודות על כל מוצר שאתם משלימים מקולקציה. לכל קולקציה ערך מימוש שמוגדר מהדשבורד.',
  'physical_boutiques': 'בוטיקים פיזיים',
  'physical_copy': 'בקרו באחד האטליות שלנו והציגו את הארנק הדיגיטלי להעלאת נקודות.',
  'rewards_experience': 'חוויית הפרסים',
  'step_browse': 'עיון',
  'step_browse_copy': 'עיינו בקטלוג האוצר של ניחוחות נישה ותוספות בוטיק.',
  'step_collect': 'איסוף',
  'step_collect_copy': 'הנקודות מתווספות אוטומטית לארנק הדיגיטלי לאחר תשלום מוצלח.',
  'step_redeem': 'מימוש',
  'step_redeem_copy': 'השתמשו בנקודות להנחות בלעדיות, גישה לאטליה או חוויות מתנה.',
  'rewards': 'פרסים',
  'exclusive_rewards': 'פרסים בלעדיים',
  'exclusive_rewards_copy': 'המירו נקודות לחוויות יוקרה ומהדורות מוגבלות.',
  'view_personal_rewards': 'צפו בפרסים האישיים',
  'redeem': 'מימוש',
  'redeemed': 'מומש',
  'reward_details': 'פרטי פרס',
  'how_to_use': 'איך להשתמש',
  'redeem_now': 'ממשו עכשיו',
  'redeemed_rewards': 'פרסים שמומשו',
  'your_exclusive': 'הקולקציה הבלעדית שלכם',
  'points_history': 'היסטוריית נקודות',
  'filter_transactions': 'סינון פעולות',
  'earned': 'נצברו',
  'spent': 'נוצלו',
  'order_history': 'היסטוריית הזמנות',
  'others': 'אחר',
  'recent_transactions': 'פעולות אחרונות',
  'all_orders': 'כל ההזמנות',
  'saved_items_count': 'פריטים שמורים',
  'tier_status': 'דרגת חברות',
  'explore_saved_items': 'גלו פריטים שמורים',
  'profile_and_settings': 'פרופיל והגדרות',
  'settings': 'הגדרות',
  'edit_profile': 'עריכת פרופיל',
  'security': 'אבטחה',
  'logout': 'התנתקות',
  'save_changes': 'שמירת שינויים',
  'update_password': 'עדכון סיסמה',
  'current_password': 'סיסמה נוכחית',
  'new_password': 'סיסמה חדשה',
  'confirm_password': 'אימות סיסמה',
  'update_password_btn': 'עדכון סיסמה',
  'stay_inspired': 'הישארו בהשראה',
  'preference_center': 'מרכז העדפות',
  'preference_copy': 'בחרו אילו סיפורי ניחוח יגיעו אליכם.',
  'promotional_offers': 'הצעות קידום',
  'exclusive_releases': 'השקות בלעדיות',
  'member_status_update': 'עדכון סטטוס חבר',
  'saved_items': 'פריטים שמורים',
  'your_private_collection': 'הקולקציה הפרטית שלכם',
  'write_a_review': 'כתבו ביקורת',
  'already_reviewed': 'כבר נכתבה ביקורת',
  'share_thoughts': 'שתפו את דעתכם',
  'publish_review': 'פרסמו ביקורת',
  'branches': 'סניפים',
  'physical_ateliers': 'אטליה פיזי',
  'branches_intro':
      'חוו את הניחוחות באופן אישי. כל אטליה הוא מקדש חושי שמשקף את המחויבות לאלגנטיות בלתי נראית.',
  'search_city': 'חיפוש עיר או רחוב...',
  'branch_details': 'פרטי סניף',
  'flagship_boutique': 'בוטיק דגל',
  'address': 'כתובת',
  'contact': 'יצירת קשר',
  'hours': 'שעות',
  'required_field': 'שדה זה חובה',
  'invalid_email': 'הזינו אימייל תקין',
  'invalid_phone': 'הזינו מספר טלפון תקין',
  'invalid_password': 'הסיסמה חייבת להכיל לפחות 6 תווים',
  'password_mismatch': 'הסיסמאות אינן תואמות',
  'invalid_code': 'הזינו קוד בן 6 ספרות',
  'login_failed': 'לא ניתן להתחבר עם פרטים אלה',
  'empty_cart': 'הקולקציה ריקה',
  'empty_saved': 'אין עדיין פריטים שמורים',
  'empty_orders': 'אין עדיין הזמנות',
  'empty_rewards': 'אין עדיין פרסים שמומשו',
  'retry': 'נסו שוב',
  'floral': 'פרחוני',
  'woody': 'עצי',
  'oriental': 'אוריינטלי',
  'fresh': 'רענן',
  'leather': 'עור',
  'gourmand': 'גורמה',
  'fresh_citrus': 'הדרים רעננים',
  'language': 'שפה',
  'resend_in': 'שליחה מחדש בעוד %sש',
  'qty': 'כמות',
  'remove': 'הסרה',
  'not_enough_points': 'אין מספיק נקודות',
  'already_redeemed': 'כבר מומש',
  'card_invalid': 'הזינו מספר כרטיס תקין',
  'expiry_invalid': 'הזינו תוקף תקין',
  'fill_shipping': 'השלימו פרטי משלוח',
  'select_payment': 'בחרו אמצעי תשלום',
  'review_hint': 'כתבו את הביקורת',
  'rating_required': 'בחרו דירוג',
  'code_sent': 'הקוד נשלח',
  'social_continue': 'המשך',
  'filter': 'סינון',
  'newest': 'החדש ביותר',
  'price': 'מחיר',
  'in_transit': 'בדרך',
  'delivered': 'נמסר',
  'processing': 'בעיבוד',
  'shipped': 'נשלח',
  'order_placed': 'ההזמנה נוצרה',
  'estimated_arrival': 'הגעה משוערת',
  'complimentary': 'על חשבון הבית',
};
